vim.o.number = true
vim.o.relativenumber = true
vim.o.tabstop = 2
vim.o.shiftwidth = 2
vim.o.expandtab = true
vim.o.smartindent = true
vim.o.termguicolors = true
vim.o.scrolloff = 8
vim.o.wrap = false
vim.o.signcolumn = "yes"
vim.o.cursorline = true
vim.o.updatetime = 300
vim.o.ignorecase = true
vim.o.smartcase = true
vim.o.clipboard = "unnamedplus"
-- vim.o.mouse = ""
